name: Publish Docker image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  push_to_dockerhub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/lab06_docker:$rev
          docker push ${{ secrets.DOCKER_USERNAME }}/lab06_docker:$rev

      - name: Log out from DockerHub
        run: docker logout
